---
eureka:
  client:
    enabled: "true"
    register-with-eureka: "true"
    serviceUrl:
      defaultZone: http://eurekahost:8010/eureka/
  instance:
    prefer-ip-address: true
server:
  port: ${PORT:${SERVER_PORT:0}}   # Select any available port if neither port nor server port are specified.
logging:
  level:
    org:
      springframework: INFO
      hibernate: INFO
      apache:
        camel:
          component:
            rabbitmq: INFO
    com:
      nanthealth: TRACE
      isirona: TRACE
