---
server:
  port: 51607
omron:
  clientId: nanthealth-api
  clientSecret: f110fcc4-5bbc-4350-ad57-3b4520339bfa
  scope: bloodpressure+activity+openid+offline_access
  redirectUri: omron://callback
  accessTokenUrl: https://ohi-oauth.numerasocial.com/connect/token
  refreshTokenUrl: https://ohi-oauth.numerasocial.com/connect/token
  dataUrl: https://ohi-api.numerasocial.com/api/measurement
  tenantId: tenant
  event:
    publisher:
      internal:
        endpoint: vm:rawReadings
      endpoint:
        log: log:marshalled
      external:
        event:
          bus:
            topic:
              endpoint: ${omron.message.broker.type}://${omron.message.broker.hostname}:${omron.message.broker.port}/${omron.message.broker.producer.exchange.name}${omron.message.broker.producer.options}
  message:
    broker:
      hostname: rabbitmq
      type: rabbitmq
      port: 5672
      producer:
        exchange:
          name: rawReadings
        options: ?exchangeType=fanout&autoDelete=false
spring:
  rabbitmq:
    listener:
      default-requeue-rejected: false
      
