---
eureka:
  instance:
    hostname: patient
patient:
  message:
    broker:
      hostname: rabbitmq
      port: 5672
  service:
    endpoint:
      log: log:marshalled
    internal:
      endpoint: vm:patientEventQueue
    external: 
      topic: rabbitmq://rabbitmq:5672/PatientEvents?exchangeType=topic
    consumer:
      external:
        topic: rabbitmq://rabbitmq:5672/ConsumerPatientEvents?exchangeType=topic
      internal:
        endpoint: vm:patientConsumerEventQueue
spring:
  data:
    mongodb:
      host: patientmongo
      port: 27017
server:
  port: 51606
