---
spring:
  datasource:
    url: jdbc:mysql://sourcesql/sources
    username: sa
    password: n0ne@H0me
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
