---
eureka:
  client:
    serviceUrl:
      defaultZone: http://win-disgu1v7isr:8011/eureka/,http://win-disgu1v7isr:8012/eureka/,http://win-disgu1v7isr:8013/eureka/
server:
  port: ${PORT:${SERVER_PORT:0}}   # Select any available port if neither port nor server port are specified.
logging:
  file: ${java.io.tmpdir}/${spring.application.name}.log
  config: file:c:/acx/log4j.properties
#  file: ${java.io.tmpdir}/${spring.application.name}.log
