---
server:
  port: 51006
spring:
  datasource:
    url: jdbc:sqlserver://10.1.134.18:1433;databaseName=dimsdeviceservice
    username: sa
    password: n0ne@H0me
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
