---
server:
  port: 51006
spring:
  data:
    mongodb:
      host: 10.1.136.18
      port: 27017
  datasource:
    url: jdbc:sqlserver://10.1.134.18:1433;databaseName=dimsdeviceservice
    username: sa
    password: n0ne@H0me
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
device:
  message:
    broker:
      type: rabbitmq
      port: 5672
      hostname: localhost
      producer:
        options: ?exchangeType=fanout&durable&username=${rabbitmq.username}&password=${rabbitmq.password}
        exchange:
          name: deviceEvents
  event:
    producer:
      topic: ${device.message.broker.type}://${device.message.broker.hostname}:${device.message.broker.port}/${device.message.broker.producer.exchange.name}${device.message.broker.producer.options}
rabbitmq:
  username: guest
  password: guest
