---
server:
  port: 51604
spring:
  datasource:
    url: jdbc:sqlserver://medusa:1433;databaseName=nanthealthprofile
    username: sa
    password: n0ne@H0me
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
